jobs:
  - name: mysql_customers
    source:
      type: mysql
      host: localhost
      port: 3306
      user: root
      password: password
      database: sample_db
      query: "SELECT * FROM customers"
    target:
      bucket: my-etl-bucket
      table: customers_table
      format: parquet
